"""create initial catalog"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial_catalog"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=35), nullable=False),
        sa.Column("retired_at", sa.String(length=35), nullable=True),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_authors_id_uuid7"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
    )
    op.create_table(
        "catalog_meta",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("schema_contract_version", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "schema_contract_version = 'catalog-v1'",
            name=op.f("ck_catalog_meta_schema_contract_version"),
        ),
        sa.CheckConstraint("revision >= 0", name=op.f("ck_catalog_meta_revision_non_negative")),
        sa.CheckConstraint("singleton_id = 1", name=op.f("ck_catalog_meta_singleton")),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_catalog_meta")),
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=35), nullable=False),
        sa.Column("updated_at", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_collections_id_uuid7"),
        ),
        sa.CheckConstraint(
            "slug <> '' AND title <> ''", name=op.f("ck_collections_identity_nonempty")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("slug", name=op.f("uq_collections_slug")),
    )
    op.create_table(
        "ingestion_run_selected_records",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("selection_ordinal", sa.Integer(), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("record_ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "record_ordinal >= 0",
            name=op.f("ck_ingestion_run_selected_records_record_ordinal_non_negative"),
        ),
        sa.CheckConstraint(
            "selection_ordinal >= 0",
            name=op.f("ck_ingestion_run_selected_records_selection_ordinal_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "source_snapshot_id"],
            ["ingestion_run_snapshots.run_id", "ingestion_run_snapshots.source_snapshot_id"],
            name=op.f("fk_ingestion_run_selected_records_run_id_ingestion_run_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "record_ordinal"],
            ["snapshot_records.source_snapshot_id", "snapshot_records.ordinal"],
            name=op.f("fk_ingestion_run_selected_records_source_snapshot_id_snapshot_records"),
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "selection_ordinal", name=op.f("pk_ingestion_run_selected_records")
        ),
        sa.UniqueConstraint(
            "run_id", "source_snapshot_id", "record_ordinal", name="uq_run_selected_record"
        ),
    )
    op.create_table(
        "papers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_papers_id_uuid7"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_papers")),
    )
    op.create_table(
        "snapshot_records",
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source_item_id", sa.Text(), nullable=True),
        sa.Column("source_version_key", sa.Text(), nullable=True),
        sa.Column("raw_record_sha256", sa.String(length=64), nullable=False),
        sa.Column("version_observation_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "length(raw_record_sha256) = 64 AND raw_record_sha256 NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_snapshot_records_raw_record_sha256"),
        ),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_snapshot_records_ordinal_non_negative")),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_snapshot_records_source_snapshot_id_source_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id"],
            ["version_observations.id"],
            name=op.f("fk_snapshot_records_version_observation_id_version_observations"),
        ),
        sa.PrimaryKeyConstraint("source_snapshot_id", "ordinal", name=op.f("pk_snapshot_records")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("terms_url", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.CheckConstraint("id <> ''", name=op.f("ck_sources_id_nonempty")),
        sa.CheckConstraint("enabled IN (0, 1)", name=op.f("ck_sources_enabled_boolean")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "stored_blobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_stored_blobs_id_uuid7"),
        ),
        sa.CheckConstraint(
            "length(sha256) = 64 AND sha256 NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_stored_blobs_sha256"),
        ),
        sa.CheckConstraint("media_type <> ''", name=op.f("ck_stored_blobs_media_type_nonempty")),
        sa.CheckConstraint(
            "relative_path <> '' AND substr(relative_path, 1, 1) <> '/' AND relative_path NOT LIKE '%..%'",
            name=op.f("ck_stored_blobs_relative_path_confined"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_stored_blobs_size_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_blobs")),
        sa.UniqueConstraint("sha256", name=op.f("uq_stored_blobs_sha256")),
    )
    op.create_table(
        "version_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_version_id", sa.String(length=36), nullable=False),
        sa.Column("normalized_sha256", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.String(length=35), nullable=False),
        sa.Column("origin_source_id", sa.String(length=64), nullable=False),
        sa.Column("origin_run_id", sa.String(length=36), nullable=False),
        sa.Column("origin_source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("origin_record_ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("journal_reference", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.String(length=35), nullable=True),
        sa.Column("announced_at", sa.String(length=35), nullable=True),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_version_observations_id_uuid7"),
        ),
        sa.CheckConstraint(
            "length(normalized_sha256) = 64 AND normalized_sha256 NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_version_observations_normalized_sha256"),
        ),
        sa.CheckConstraint("title <> ''", name=op.f("ck_version_observations_title_nonempty")),
        sa.CheckConstraint(
            "title_normalized <> ''", name=op.f("ck_version_observations_title_normalized_nonempty")
        ),
        sa.CheckConstraint(
            "origin_record_ordinal >= 0",
            name=op.f("ck_version_observations_origin_record_ordinal_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_run_id", "origin_source_id"],
            ["ingestion_runs.id", "ingestion_runs.source_id"],
            name=op.f("fk_version_observations_origin_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_run_id", "origin_source_snapshot_id", "origin_record_ordinal"],
            [
                "ingestion_run_selected_records.run_id",
                "ingestion_run_selected_records.source_snapshot_id",
                "ingestion_run_selected_records.record_ordinal",
            ],
            name=op.f("fk_version_observations_origin_run_id_ingestion_run_selected_records"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_source_snapshot_id", "origin_source_id"],
            ["source_snapshots.id", "source_snapshots.source_id"],
            name=op.f("fk_version_observations_origin_source_snapshot_id_source_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.id"],
            name=op.f("fk_version_observations_paper_version_id_paper_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id", "origin_source_id"],
            ["paper_versions.id", "paper_versions.source_id"],
            name=op.f("fk_version_observations_paper_version_id_paper_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_version_observations")),
        sa.UniqueConstraint("id", "origin_source_id", name="uq_observation_source"),
        sa.UniqueConstraint("id", "paper_version_id", name="uq_observation_version"),
        sa.UniqueConstraint(
            "paper_version_id", "normalized_sha256", name="uq_version_observation_hash"
        ),
    )
    op.create_table(
        "author_identifiers",
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("canonical_value", sa.Text(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("verified_at", sa.String(length=35), nullable=True),
        sa.CheckConstraint(
            "scheme <> '' AND canonical_value <> '' AND verification_status <> ''",
            name=op.f("ck_author_identifiers_identity_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["authors.id"], name=op.f("fk_author_identifiers_author_id_authors")
        ),
        sa.PrimaryKeyConstraint("scheme", "canonical_value", name=op.f("pk_author_identifiers")),
    )
    op.create_table(
        "collection_papers",
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("added_at", sa.String(length=35), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_papers_collection_id_collections"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name=op.f("fk_collection_papers_paper_id_papers")
        ),
        sa.PrimaryKeyConstraint("collection_id", "paper_id", name=op.f("pk_collection_papers")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("prepared_digest", sa.String(length=64), nullable=False),
        sa.Column("query_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.String(length=35), nullable=False),
        sa.Column("finished_at", sa.String(length=35), nullable=True),
        sa.Column("selected_records", sa.Integer(), nullable=False),
        sa.Column("new_papers", sa.Integer(), server_default="0", nullable=False),
        sa.Column("new_versions", sa.Integer(), server_default="0", nullable=False),
        sa.Column("metadata_updates", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unchanged_records", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_records", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "(status = 'running' AND finished_at IS NULL) OR (status <> 'running' AND finished_at IS NOT NULL AND selected_records = new_versions + metadata_updates + unchanged_records + failed_records)",
            name=op.f("ck_ingestion_runs_final_state"),
        ),
        sa.CheckConstraint(
            "json_extract(query_json, '$.schema_version') = 'discovery-query-v1'",
            name=op.f("ck_ingestion_runs_query_json_schema"),
        ),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_ingestion_runs_id_uuid7"),
        ),
        sa.CheckConstraint(
            "length(prepared_digest) = 64 AND prepared_digest NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_ingestion_runs_prepared_digest"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'partial', 'failed')",
            name=op.f("ck_ingestion_runs_status"),
        ),
        sa.CheckConstraint(
            "json_valid(query_json)", name=op.f("ck_ingestion_runs_query_json_valid")
        ),
        sa.CheckConstraint(
            "new_papers <= new_versions", name=op.f("ck_ingestion_runs_new_papers_bounded")
        ),
        sa.CheckConstraint(
            "selected_records >= 0 AND new_papers >= 0 AND new_versions >= 0 AND metadata_updates >= 0 AND unchanged_records >= 0 AND failed_records >= 0",
            name=op.f("ck_ingestion_runs_counters_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_ingestion_runs_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
        sa.UniqueConstraint("id", "source_id", name="uq_run_source"),
    )
    op.create_table(
        "paper_authors",
        sa.Column("version_observation_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("raw_name", sa.Text(), nullable=False),
        sa.Column("affiliation_raw", sa.Text(), nullable=True),
        sa.CheckConstraint("raw_name <> ''", name=op.f("ck_paper_authors_raw_name_nonempty")),
        sa.CheckConstraint("position >= 1", name=op.f("ck_paper_authors_position_positive")),
        sa.ForeignKeyConstraint(
            ["author_id"], ["authors.id"], name=op.f("fk_paper_authors_author_id_authors")
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id"],
            ["version_observations.id"],
            name=op.f("fk_paper_authors_version_observation_id_version_observations"),
        ),
        sa.PrimaryKeyConstraint(
            "version_observation_id", "position", name=op.f("pk_paper_authors")
        ),
    )
    op.create_table(
        "paper_identifiers",
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("canonical_value", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.String(length=35), nullable=True),
        sa.CheckConstraint(
            "scheme <> '' AND canonical_value <> ''",
            name=op.f("ck_paper_identifiers_identity_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name=op.f("fk_paper_identifiers_paper_id_papers")
        ),
        sa.PrimaryKeyConstraint("scheme", "canonical_value", name=op.f("pk_paper_identifiers")),
    )
    op.create_table(
        "paper_version_categories",
        sa.Column("version_observation_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "category <> ''", name=op.f("ck_paper_version_categories_category_nonempty")
        ),
        sa.CheckConstraint(
            "is_primary IN (0, 1)", name=op.f("ck_paper_version_categories_is_primary_boolean")
        ),
        sa.CheckConstraint(
            "position >= 1", name=op.f("ck_paper_version_categories_position_positive")
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id"],
            ["version_observations.id"],
            name=op.f("fk_paper_version_categories_version_observation_id_version_observations"),
        ),
        sa.PrimaryKeyConstraint(
            "version_observation_id", "position", name=op.f("pk_paper_version_categories")
        ),
        sa.UniqueConstraint("version_observation_id", "category", name="uq_observation_category"),
    )
    op.create_table(
        "paper_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_version_key", sa.Text(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_paper_versions_id_uuid7"),
        ),
        sa.CheckConstraint(
            "source_version_key <> ''", name=op.f("ck_paper_versions_source_version_key_nonempty")
        ),
        sa.CheckConstraint(
            "is_current IN (0, 1)", name=op.f("ck_paper_versions_is_current_boolean")
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name=op.f("fk_paper_versions_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_paper_versions_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_versions")),
        sa.UniqueConstraint("id", "paper_id", name="uq_version_paper"),
        sa.UniqueConstraint("id", "source_id", name="uq_version_source"),
        sa.UniqueConstraint("source_id", "source_version_key", name="uq_source_version"),
    )
    with op.batch_alter_table("paper_versions", schema=None) as batch_op:
        batch_op.create_index(
            "uq_paper_versions_current",
            ["paper_id", "source_id"],
            unique=True,
            sqlite_where=sa.text("is_current IS 1"),
        )

    op.create_table(
        "source_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("capture_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("stored_blob_id", sa.String(length=36), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.String(length=35), nullable=False),
        sa.Column("next_cursor", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "length(capture_id) = 36 AND substr(capture_id, 9, 1) = '-' AND substr(capture_id, 14, 1) = '-' AND substr(capture_id, 15, 1) = '7' AND substr(capture_id, 19, 1) = '-' AND lower(substr(capture_id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(capture_id, 24, 1) = '-' AND replace(capture_id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_source_snapshots_capture_id_uuid7"),
        ),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_source_snapshots_id_uuid7"),
        ),
        sa.CheckConstraint(
            "length(request_fingerprint) = 64 AND request_fingerprint NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_source_snapshots_request_fingerprint"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_source_snapshots_source_id_sources")
        ),
        sa.ForeignKeyConstraint(
            ["stored_blob_id"],
            ["stored_blobs.id"],
            name=op.f("fk_source_snapshots_stored_blob_id_stored_blobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
        sa.UniqueConstraint("capture_id", name=op.f("uq_source_snapshots_capture_id")),
        sa.UniqueConstraint("id", "source_id", name="uq_snapshot_source"),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("paper_version_id", sa.String(length=36), nullable=False),
        sa.Column("version_observation_id", sa.String(length=36), nullable=True),
        sa.Column("stored_blob_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("parent_artifact_id", sa.String(length=36), nullable=True),
        sa.Column("producer_name", sa.Text(), nullable=True),
        sa.Column("producer_version", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "kind <> 'metadata' OR version_observation_id IS NOT NULL",
            name=op.f("ck_artifacts_metadata_observation"),
        ),
        sa.CheckConstraint(
            "kind IN ('metadata', 'pdf', 'text', 'analysis')", name=op.f("ck_artifacts_kind")
        ),
        sa.CheckConstraint(
            "length(id) = 36 AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-' AND substr(id, 15, 1) = '7' AND substr(id, 19, 1) = '-' AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b') AND substr(id, 24, 1) = '-' AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'",
            name=op.f("ck_artifacts_id_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.id"],
            name=op.f("fk_artifacts_paper_version_id_paper_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_artifacts_parent_artifact_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["stored_blob_id"],
            ["stored_blobs.id"],
            name=op.f("fk_artifacts_stored_blob_id_stored_blobs"),
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id", "paper_version_id"],
            ["version_observations.id", "version_observations.paper_version_id"],
            name=op.f("fk_artifacts_version_observation_id_version_observations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint(
            "paper_version_id", "kind", "stored_blob_id", name="uq_version_artifact"
        ),
    )
    op.create_table(
        "author_identifier_evidence",
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("canonical_value", sa.Text(), nullable=False),
        sa.Column("version_observation_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("observed_at", sa.String(length=35), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheme", "canonical_value"],
            ["author_identifiers.scheme", "author_identifiers.canonical_value"],
            name=op.f("fk_author_identifier_evidence_scheme_author_identifiers"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_author_identifier_evidence_source_id_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id"],
            ["version_observations.id"],
            name=op.f("fk_author_identifier_evidence_version_observation_id_version_observations"),
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id", "source_id"],
            ["version_observations.id", "version_observations.origin_source_id"],
            name=op.f("fk_author_identifier_evidence_version_observation_id_version_observations"),
        ),
        sa.PrimaryKeyConstraint(
            "scheme",
            "canonical_value",
            "version_observation_id",
            name=op.f("pk_author_identifier_evidence"),
        ),
    )
    op.create_table(
        "ingestion_run_items",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("record_ordinal", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.String(length=36), nullable=True),
        sa.Column("paper_version_id", sa.String(length=36), nullable=True),
        sa.Column("version_observation_id", sa.String(length=36), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("created_paper", sa.Boolean(), nullable=False),
        sa.Column("recorded_at", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "(outcome = 'failed' AND paper_id IS NULL AND paper_version_id IS NULL AND version_observation_id IS NULL AND created_paper = 0) OR (outcome <> 'failed' AND paper_id IS NOT NULL AND paper_version_id IS NOT NULL AND version_observation_id IS NOT NULL)",
            name=op.f("ck_ingestion_run_items_outcome_references"),
        ),
        sa.CheckConstraint(
            "created_paper = 0 OR outcome = 'new_version'",
            name=op.f("ck_ingestion_run_items_created_paper_outcome"),
        ),
        sa.CheckConstraint(
            "outcome IN ('new_version', 'metadata_update', 'unchanged', 'failed')",
            name=op.f("ck_ingestion_run_items_outcome"),
        ),
        sa.CheckConstraint(
            "created_paper IN (0, 1)", name=op.f("ck_ingestion_run_items_created_paper_boolean")
        ),
        sa.CheckConstraint(
            "record_ordinal >= 0", name=op.f("ck_ingestion_run_items_record_ordinal_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name=op.f("fk_ingestion_run_items_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id", "paper_id"],
            ["paper_versions.id", "paper_versions.paper_id"],
            name=op.f("fk_ingestion_run_items_paper_version_id_paper_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.id"],
            name=op.f("fk_ingestion_run_items_paper_version_id_paper_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "source_snapshot_id", "record_ordinal"],
            [
                "ingestion_run_selected_records.run_id",
                "ingestion_run_selected_records.source_snapshot_id",
                "ingestion_run_selected_records.record_ordinal",
            ],
            name=op.f("fk_ingestion_run_items_run_id_ingestion_run_selected_records"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_ingestion_run_items_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id", "paper_version_id"],
            ["version_observations.id", "version_observations.paper_version_id"],
            name=op.f("fk_ingestion_run_items_version_observation_id_version_observations"),
        ),
        sa.ForeignKeyConstraint(
            ["version_observation_id"],
            ["version_observations.id"],
            name=op.f("fk_ingestion_run_items_version_observation_id_version_observations"),
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "source_snapshot_id", "record_ordinal", name=op.f("pk_ingestion_run_items")
        ),
    )
    op.create_table(
        "ingestion_run_snapshots",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("page_ordinal", sa.Integer(), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "page_ordinal >= 0", name=op.f("ck_ingestion_run_snapshots_page_ordinal_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "source_id"],
            ["ingestion_runs.id", "ingestion_runs.source_id"],
            name=op.f("fk_ingestion_run_snapshots_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "source_id"],
            ["source_snapshots.id", "source_snapshots.source_id"],
            name=op.f("fk_ingestion_run_snapshots_source_snapshot_id_source_snapshots"),
        ),
        sa.PrimaryKeyConstraint("run_id", "page_ordinal", name=op.f("pk_ingestion_run_snapshots")),
        sa.UniqueConstraint("run_id", "source_snapshot_id", name="uq_run_snapshot"),
    )
    op.create_table(
        "paper_identifier_evidence",
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("canonical_value", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("record_ordinal", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.String(length=35), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheme", "canonical_value"],
            ["paper_identifiers.scheme", "paper_identifiers.canonical_value"],
            name=op.f("fk_paper_identifier_evidence_scheme_paper_identifiers"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_paper_identifier_evidence_source_id_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "record_ordinal"],
            ["snapshot_records.source_snapshot_id", "snapshot_records.ordinal"],
            name=op.f("fk_paper_identifier_evidence_source_snapshot_id_snapshot_records"),
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "source_id"],
            ["source_snapshots.id", "source_snapshots.source_id"],
            name=op.f("fk_paper_identifier_evidence_source_snapshot_id_source_snapshots"),
        ),
        sa.PrimaryKeyConstraint(
            "scheme",
            "canonical_value",
            "source_snapshot_id",
            "record_ordinal",
            name=op.f("pk_paper_identifier_evidence"),
        ),
    )
    op.create_table(
        "version_identifiers",
        sa.Column("paper_version_id", sa.String(length=36), nullable=False),
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("canonical_value", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.String(length=35), nullable=True),
        sa.CheckConstraint(
            "scheme <> '' AND canonical_value <> ''",
            name=op.f("ck_version_identifiers_identity_nonempty"),
        ),
        sa.ForeignKeyConstraint(
            ["paper_version_id"],
            ["paper_versions.id"],
            name=op.f("fk_version_identifiers_paper_version_id_paper_versions"),
        ),
        sa.PrimaryKeyConstraint("scheme", "canonical_value", name=op.f("pk_version_identifiers")),
    )
    op.create_table(
        "collection_errors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("record_ordinal", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.String(length=35), nullable=False),
        sa.CheckConstraint(
            "(stage = 'catalog_write' AND code IN ('record_invalid', 'artifact_invalid', 'catalog_conflict')) OR (stage = 'recovery' AND code = 'interrupted')",
            name=op.f("ck_collection_errors_stage_code"),
        ),
        sa.CheckConstraint(
            "code <> '' AND message <> ''", name=op.f("ck_collection_errors_public_error_nonempty")
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "source_snapshot_id", "record_ordinal"],
            [
                "ingestion_run_items.run_id",
                "ingestion_run_items.source_snapshot_id",
                "ingestion_run_items.record_ordinal",
            ],
            name=op.f("fk_collection_errors_run_id_ingestion_run_items"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_collection_errors_run_id_ingestion_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_errors")),
        sa.UniqueConstraint(
            "run_id", "source_snapshot_id", "record_ordinal", name="uq_collection_error_item"
        ),
    )
    op.create_table(
        "version_identifier_evidence",
        sa.Column("scheme", sa.String(length=32), nullable=False),
        sa.Column("canonical_value", sa.Text(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("record_ordinal", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.String(length=35), nullable=False),
        sa.ForeignKeyConstraint(
            ["scheme", "canonical_value"],
            ["version_identifiers.scheme", "version_identifiers.canonical_value"],
            name=op.f("fk_version_identifier_evidence_scheme_version_identifiers"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_version_identifier_evidence_source_id_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "record_ordinal"],
            ["snapshot_records.source_snapshot_id", "snapshot_records.ordinal"],
            name=op.f("fk_version_identifier_evidence_source_snapshot_id_snapshot_records"),
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id", "source_id"],
            ["source_snapshots.id", "source_snapshots.source_id"],
            name=op.f("fk_version_identifier_evidence_source_snapshot_id_source_snapshots"),
        ),
        sa.PrimaryKeyConstraint(
            "scheme",
            "canonical_value",
            "source_snapshot_id",
            "record_ordinal",
            name=op.f("pk_version_identifier_evidence"),
        ),
    )
    op.execute(
        "CREATE TRIGGER artifacts_metadata_digest_insert "
        "BEFORE INSERT ON artifacts WHEN NEW.kind = 'metadata' AND NOT EXISTS ("
        "SELECT 1 FROM version_observations AS vo "
        "JOIN stored_blobs AS b ON b.id = NEW.stored_blob_id "
        "WHERE vo.id = NEW.version_observation_id "
        "AND vo.paper_version_id = NEW.paper_version_id "
        "AND b.sha256 = vo.normalized_sha256) "
        "BEGIN SELECT RAISE(ABORT, 'metadata artifact digest mismatch'); END"
    )
    op.execute(
        "CREATE TRIGGER artifacts_metadata_digest_update "
        "BEFORE UPDATE OF paper_version_id, version_observation_id, stored_blob_id, kind "
        "ON artifacts WHEN NEW.kind = 'metadata' AND NOT EXISTS ("
        "SELECT 1 FROM version_observations AS vo "
        "JOIN stored_blobs AS b ON b.id = NEW.stored_blob_id "
        "WHERE vo.id = NEW.version_observation_id "
        "AND vo.paper_version_id = NEW.paper_version_id "
        "AND b.sha256 = vo.normalized_sha256) "
        "BEGIN SELECT RAISE(ABORT, 'metadata artifact digest mismatch'); END"
    )
    op.execute(
        "CREATE TRIGGER snapshot_records_source_insert "
        "BEFORE INSERT ON snapshot_records WHEN NEW.version_observation_id IS NOT NULL "
        "AND NOT EXISTS(SELECT 1 FROM source_snapshots AS ss "
        "JOIN version_observations AS vo ON vo.id = NEW.version_observation_id "
        "WHERE ss.id = NEW.source_snapshot_id AND ss.source_id = vo.origin_source_id) "
        "BEGIN SELECT RAISE(ABORT, 'snapshot observation source mismatch'); END"
    )
    op.execute(
        "CREATE TRIGGER snapshot_records_source_update "
        "BEFORE UPDATE OF source_snapshot_id, version_observation_id ON snapshot_records "
        "WHEN NEW.version_observation_id IS NOT NULL AND NOT EXISTS("
        "SELECT 1 FROM source_snapshots AS ss "
        "JOIN version_observations AS vo ON vo.id = NEW.version_observation_id "
        "WHERE ss.id = NEW.source_snapshot_id AND ss.source_id = vo.origin_source_id) "
        "BEGIN SELECT RAISE(ABORT, 'snapshot observation source mismatch'); END"
    )
    op.execute(
        "CREATE TRIGGER ingestion_run_items_source_insert "
        "BEFORE INSERT ON ingestion_run_items WHEN NEW.outcome <> 'failed' AND NOT EXISTS("
        "SELECT 1 FROM ingestion_runs AS run "
        "JOIN paper_versions AS version ON version.id = NEW.paper_version_id "
        "JOIN version_observations AS observation "
        "ON observation.id = NEW.version_observation_id WHERE run.id = NEW.run_id "
        "AND run.source_id = version.source_id "
        "AND run.source_id = observation.origin_source_id) "
        "BEGIN SELECT RAISE(ABORT, 'ingestion item source mismatch'); END"
    )
    op.execute(
        "CREATE TRIGGER ingestion_run_items_source_update "
        "BEFORE UPDATE OF run_id, source_snapshot_id, paper_version_id, "
        "version_observation_id, outcome ON ingestion_run_items "
        "WHEN NEW.outcome <> 'failed' AND NOT EXISTS("
        "SELECT 1 FROM ingestion_runs AS run "
        "JOIN paper_versions AS version ON version.id = NEW.paper_version_id "
        "JOIN version_observations AS observation "
        "ON observation.id = NEW.version_observation_id WHERE run.id = NEW.run_id "
        "AND run.source_id = version.source_id "
        "AND run.source_id = observation.origin_source_id) "
        "BEGIN SELECT RAISE(ABORT, 'ingestion item source mismatch'); END"
    )
    op.execute(
        "INSERT INTO catalog_meta "
        "(singleton_id, revision, schema_contract_version) VALUES (1, 0, 'catalog-v1')"
    )
    op.execute(
        "INSERT INTO sources (id, base_url, terms_url, enabled) VALUES "
        "('arxiv', 'https://export.arxiv.org', "
        "'https://info.arxiv.org/help/api/tou.html', 1)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("version_identifier_evidence")
    op.drop_table("collection_errors")
    op.drop_table("author_identifier_evidence")
    op.drop_table("paper_identifier_evidence")
    op.drop_table("artifacts")
    op.drop_table("collection_papers")
    op.drop_table("paper_version_categories")
    op.drop_table("paper_authors")
    op.drop_table("ingestion_run_items")
    op.drop_table("version_identifiers")
    op.drop_table("paper_identifiers")
    # Snapshot provenance is cyclic by design. Break its nullable resolution
    # edge before dropping the remaining tables in child-to-parent order.
    op.execute("UPDATE snapshot_records SET version_observation_id = NULL")
    op.drop_table("version_observations")
    op.drop_table("ingestion_run_selected_records")
    op.drop_table("snapshot_records")
    op.drop_table("ingestion_run_snapshots")
    with op.batch_alter_table("paper_versions", schema=None) as batch_op:
        batch_op.drop_index("uq_paper_versions_current", sqlite_where=sa.text("is_current IS 1"))

    op.drop_table("paper_versions")
    op.drop_table("ingestion_runs")
    op.drop_table("author_identifiers")
    op.drop_table("source_snapshots")
    op.drop_table("stored_blobs")
    op.drop_table("papers")
    op.drop_table("collections")
    op.drop_table("authors")
    op.drop_table("sources")
    op.drop_table("catalog_meta")
    # ### end Alembic commands ###
